/**
 * Fotoverantwoording. Automatisch gegenereerd uit de metadata van Wikimedia Commons;
 * alle foto's zijn vrij te gebruiken onder de genoemde licentie, met naamsvermelding.
 */

export type PhotoCredit = {
  file: string;
  title: string;
  author: string;
  license: string;
  licenseUrl: string;
  source: string;
  width: number;
  height: number;
};

export const PHOTO_CREDITS: PhotoCredit[] = [
  {
    file: "/images/tours/lempuyang-tirta-gangga.jpg",
    title: "\"Heaven Gate\" Pura Lempuyang.jpg",
    author: "Chainwit.",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:%22Heaven_Gate%22_Pura_Lempuyang.jpg",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/boer-rijstveld.jpg",
    title: "A female farmer is planting rice seedlings.jpg",
    author: "Hariyono Suwardi",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:A_female_farmer_is_planting_rice_seedlings.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/atv-quad.jpg",
    title: "ATV Motor.jpg",
    author: "Ivu Fajar Samsumar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:ATV_Motor.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/rafting-ayung.jpg",
    title: "Ayung River Rafting 2, Bali.jpg",
    author: "Yoshi Canopus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ayung_River_Rafting_2,_Bali.jpg",
    width: 1920,
    height: 1275,
  },
  {
    file: "/images/tours/bali-swing.jpg",
    title: "Bali Swing.jpg",
    author: "RienShin14",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bali_Swing.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/barong.jpg",
    title: "Barong Tanah Kilap - 2025-02-15 - Andy Mabbett - 12.jpg",
    author: "Andy Mabbett",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Barong_Tanah_Kilap_-_2025-02-15_-_Andy_Mabbett_-_12.jpg",
    width: 1920,
    height: 1285,
  },
  {
    file: "/images/tours/besakih-sidemen.jpg",
    title: "Besakih Bali Indonesia Pura-Besakih-02.jpg",
    author: "CEphoto, Uwe Aranas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Besakih_Bali_Indonesia_Pura-Besakih-02.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/snorkelen-padangbai.jpg",
    title: "Biru Lautan.jpg",
    author: "Eka Purna Sumeika",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Biru_Lautan.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/campuhan-ridge.jpg",
    title: "Campuhan ridge walk Ubud Bali 20120827b.jpg",
    author: "Tigerente",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Campuhan_ridge_walk_Ubud_Bali_20120827b.jpg",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/canang-sari.jpg",
    title: "Canang sari 1.jpg",
    author: "Mx. Granger",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Canang_sari_1.jpg",
    width: 1920,
    height: 1546,
  },
  {
    file: "/images/tours/nusa-penida-oost.jpg",
    title: "Diamond Beach aerial 2026 01.jpg",
    author: "FBilula",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Diamond_Beach_aerial_2026_01.jpg",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/sekumpul-waterval.jpg",
    title: "Gitgit waterfalls in Bali; January 2015.jpg",
    author: "Juan Antonio F. Segal from Madrid, Spain",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Gitgit_waterfalls_in_Bali;_January_2015.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/goa-gajah.jpg",
    title: "Goa Gajah temple, Bedulu, Bali, Indonesia, 20220824 0923 0526.jpg",
    author: "Jakub Hałun",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Goa_Gajah_temple,_Bedulu,_Bali,_Indonesia,_20220824_0923_0526.jpg",
    width: 1920,
    height: 1282,
  },
  {
    file: "/images/tours/bali-safari.jpg",
    title: "I had seen this White Rhino from elephant back as well (44284065860).jpg",
    author: "shankar s. from Poona (pune), India, India",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:I_had_seen_this_White_Rhino_from_elephant_back_as_well_(44284065860).jpg",
    width: 1920,
    height: 1282,
  },
  {
    file: "/images/tours/jatiluwih.jpg",
    title: "Jatiluwih rice terraces.jpg",
    author: "Imacim",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Jatiluwih_rice_terraces.jpg",
    width: 1920,
    height: 748,
  },
  {
    file: "/images/tours/nusa-penida-west.jpg",
    title: "Kelingking Beach (T-Rex Bay) of Nusa Penida, Bali (2025) - img 07.jpg",
    author: "Chainwit.",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kelingking_Beach_(T-Rex_Bay)_of_Nusa_Penida,_Bali_(2025)_-_img_07.jpg",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/kintamani-koffie.jpg",
    title: "Kintamani - Danau Batur - 49818147221.jpg",
    author: "Jorge Franganillo",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Kintamani_-_Danau_Batur_-_49818147221.jpg",
    width: 1920,
    height: 1080,
  },
  {
    file: "/images/tours/uluwatu-kecak.jpg",
    title: "Kuta Bali Indonesia Pura-Luhur-Uluwatu-03.jpg",
    author: "CEphoto, Uwe Aranas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Kuta_Bali_Indonesia_Pura-Luhur-Uluwatu-03.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/lovina-dolfijnen.jpg",
    title: "Lovina Dolphins - panoramio.jpg",
    author: "Michelle Maria",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Lovina_Dolphins_-_panoramio.jpg",
    width: 1920,
    height: 872,
  },
  {
    file: "/images/tours/monkey-forest.jpg",
    title: "Macaca fascicularis, Ubud Monkey Forest, Bali, 20220822 1053 0056.jpg",
    author: "Jakub Hałun",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Macaca_fascicularis,_Ubud_Monkey_Forest,_Bali,_20220822_1053_0056.jpg",
    width: 1920,
    height: 1282,
  },
  {
    file: "/images/tours/manta-point.jpg",
    title: "Manta-ray-penida.jpg",
    author: "Sasuke shinozawa",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Manta-ray-penida.jpg",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/ceremonie.jpg",
    title: "Melasti ring segara.jpg",
    author: "Wiaskara",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Melasti_ring_segara.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/munduk.jpg",
    title: "Munduk air terjun 2009.jpg",
    author: "Jean-Marie Hullot",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Munduk_air_terjun_2009.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/nasi-campur.jpg",
    title: "Nasi Campur Bali Ayam Betutu.jpg",
    author: "Gunawan Kartapranata",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Nasi_Campur_Bali_Ayam_Betutu.jpg",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/kookworkshop.jpg",
    title: "Nasi campur, Ubud, Indonesia.jpg",
    author: "Vyacheslav Argenberg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Nasi_campur,_Ubud,_Indonesia.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/menjangan.jpg",
    title: "Pantai di Pulau Menjangan - TN Bali Barat.jpg",
    author: "Winsonchu95",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pantai_di_Pulau_Menjangan_-_TN_Bali_Barat.jpg",
    width: 1920,
    height: 1441,
  },
  {
    file: "/images/tours/canggu-surf.jpg",
    title: "Pantai Seminyak.jpg",
    author: "Fitri Penyalai",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pantai_Seminyak.jpg",
    width: 1920,
    height: 864,
  },
  {
    file: "/images/tours/gili-trawangan.jpg",
    title: "People on the beach, Gili Trawangan (island), Indonesia.jpg",
    author: "Vyacheslav Argenberg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:People_on_the_beach,_Gili_Trawangan_(island),_Indonesia.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/taman-ayun.jpg",
    title: "Pura Taman Ayun terletak di Mengwi, Bali.jpg",
    author: "Cindi CGJ",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pura_Taman_Ayun_terletak_di_Mengwi,_Bali.jpg",
    width: 1920,
    height: 1272,
  },
  {
    file: "/images/tours/ulun-danu-beratan.jpg",
    title: "Pura Ulun Danu Bratan 3.JPG",
    author: "Manuae",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pura_Ulun_Danu_Bratan_3.JPG",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/tirta-empul.jpg",
    title: "Purification - Tirta Empul temple (16871743809).jpg",
    author: "Jorge Láscar from Melbourne, Australia",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Purification_-_Tirta_Empul_temple_(16871743809).jpg",
    width: 1920,
    height: 1275,
  },
  {
    file: "/images/tours/sidemen-vallei.jpg",
    title: "Sidemen sawah countryside (Bali, Indonesia 2016) (30039194120).jpg",
    author: "Paul Arps from The Netherlands",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Sidemen_sawah_countryside_(Bali,_Indonesia_2016)_(30039194120).jpg",
    width: 1920,
    height: 1282,
  },
  {
    file: "/images/tours/mount-batur-zonsopgang.jpg",
    title: "Sunrise from Mount Batur.jpg",
    author: "Aaron Rentfrew",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sunrise_from_Mount_Batur.jpg",
    width: 1920,
    height: 1034,
  },
  {
    file: "/images/tours/strand-zonsondergang.jpg",
    title: "Sunset cocktails at Jimbaran Beach.JPG",
    author: "Jc8136",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Sunset_cocktails_at_Jimbaran_Beach.JPG",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/tanah-lot.jpg",
    title: "Tanah-Lot Bali Indonesia Pura-Tanah-Lot-01.jpg",
    author: "CEphoto, Uwe Aranas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Tanah-Lot_Bali_Indonesia_Pura-Tanah-Lot-01.jpg",
    width: 1920,
    height: 1280,
  },
  {
    file: "/images/tours/ubud-rijstterrassen.jpg",
    title: "Tegallalang Rice Terraces Bali.jpg",
    author: "Philip Nalangan",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Tegallalang_Rice_Terraces_Bali.jpg",
    width: 1920,
    height: 1277,
  },
  {
    file: "/images/tours/watervallen-ubud.jpg",
    title: "Tegenungan Waterfall (222403843).jpeg",
    author: "John Ellis",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Tegenungan_Waterfall_(222403843).jpeg",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/waterbom.jpg",
    title: "WaterbomParkLazyRiver.jpg",
    author: "Scoreed",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
    source: "https://commons.wikimedia.org/wiki/File:WaterbomParkLazyRiver.jpg",
    width: 1920,
    height: 1440,
  },
  {
    file: "/images/tours/amed-tulamben.jpg",
    title: "Wv Amed banner2.jpeg",
    author: "Arnas Goldberg",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Wv_Amed_banner2.jpeg",
    width: 1920,
    height: 640,
  },
];

export function creditFor(file: string) {
  return PHOTO_CREDITS.find((credit) => credit.file === file);
}
