/**
 * Alle tours van Edigidsbali. Eén bron voor de kaarten op de homepage, de
 * overzichtspagina, de detailpagina's, de sitemap en de gestructureerde data.
 *
 * Prijzen zijn richtprijzen in euro's (TODO: laat Edi ze bevestigen). Bij
 * "auto" geldt de prijs voor de privéauto met chauffeur-gids, ongeacht het
 * aantal gasten (max. MAX_GUESTS uit lib/site.ts); bij "pp" per persoon.
 * Entreegelden zijn nooit inbegrepen, tenzij anders vermeld.
 */

export type Category = "tempels" | "natuur" | "strand" | "avontuur" | "familie";

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: "tempels", label: "Tempels & cultuur" },
  { id: "natuur", label: "Natuur & rijstvelden" },
  { id: "strand", label: "Strand & eilanden" },
  { id: "avontuur", label: "Avontuur" },
  { id: "familie", label: "Familie" },
];

export function categoryLabel(id: Category) {
  return CATEGORIES.find((c) => c.id === id)?.label ?? id;
}

export type Tour = {
  slug: string;
  title: string;
  /** Eén regel onder de titel op de kaart. */
  short: string;
  category: Category;
  region: string;
  duration: string;
  priceFrom: number;
  priceUnit: "auto" | "pp";
  /** Toelichting bij de prijs, bv. wat er wel of niet in zit. */
  priceNote?: string;
  image: string;
  imageAlt: string;
  /** Tailwind object-position-klasse voor panoramische foto's. */
  imagePosition?: string;
  popular?: boolean;
  bestTime: string;
  intro: string[];
  highlights: string[];
  programma: string[];
  tips: string[];
  inbegrepen?: string[];
  nietInbegrepen?: string[];
};

export const INBEGREPEN_AUTO = [
  "Privéauto met airco en Edi als chauffeur-gids",
  "Ophalen en terugbrengen bij je verblijf in Zuid-Bali of Ubud",
  "Brandstof, parkeergeld en tol",
  "Flesjes water in de auto",
  "Flexibele route: onderweg aanpassen kan altijd",
];

export const NIET_INBEGREPEN_AUTO = [
  "Entreegelden (Edi noemt de bedragen vooraf)",
  "Maaltijden en drankjes",
  "Fooien, naar eigen inzicht",
];

export function inbegrepenVan(tour: Tour) {
  return tour.inbegrepen ?? INBEGREPEN_AUTO;
}

export function nietInbegrepenVan(tour: Tour) {
  return tour.nietInbegrepen ?? NIET_INBEGREPEN_AUTO;
}

export function formatPrice(tour: Tour) {
  const amount = `€ ${tour.priceFrom}`;
  return tour.priceUnit === "auto" ? `${amount} per auto` : `${amount} p.p.`;
}

export const TOURS: Tour[] = [
  {
    slug: "ubud-highlights",
    title: "Ubud highlights: Tegallalang, Monkey Forest & de kunstmarkt",
    short: "De klassieke kennismaking met het culturele hart van Bali",
    category: "tempels",
    region: "Ubud & Midden-Bali",
    duration: "Hele dag (± 9 uur)",
    priceFrom: 55,
    priceUnit: "auto",
    image: "/images/tours/ubud-rijstterrassen.jpg",
    imageAlt: "Groene rijstterrassen van Tegallalang met palmbomen bij Ubud",
    popular: true,
    bestTime: "Het hele jaar. Vroeg starten voor rustige rijstterrassen en zachter licht.",
    intro: [
      "Ubud is het culturele hart van Bali: rijstterrassen, tempels, kunst en een dorpsleven dat je vanuit de auto al ziet gebeuren. Op deze dag neemt Edi je mee langs de hoogtepunten, in een tempo dat bij jullie past.",
      "Je begint bij de beroemde rijstterrassen van Tegallalang voordat de bussen komen, proeft Balinese koffie op een plantage en eindigt tussen de makaken in het Monkey Forest en de kraampjes van de kunstmarkt.",
    ],
    highlights: [
      "Rijstterrassen van Tegallalang",
      "Koffieplantage met proeverij",
      "Sacred Monkey Forest",
      "Ubud-paleis (Puri Saren Agung) en de Saraswati-tempel",
      "Kunstmarkt van Ubud",
    ],
    programma: [
      "08:30 · Ophalen bij je verblijf",
      "10:00 · Wandeling door de rijstterrassen van Tegallalang",
      "11:30 · Koffieplantage: Balinese koffie en thee proeven",
      "13:00 · Lunch met uitzicht over de rijstvelden (eigen rekening)",
      "14:30 · Monkey Forest van Ubud",
      "16:00 · Ubud-paleis, Saraswati-tempel en de kunstmarkt",
      "17:30 · Terug naar je verblijf",
    ],
    tips: [
      "Neem een sarong mee of huur er een bij de tempels; schouders en knieën bedekt.",
      "Houd zonnebrillen, petjes en losse spullen goed vast in het Monkey Forest.",
      "Liever geen koffieplantage? Edi ruilt hem zo in voor de Tirta Empul-tempel.",
    ],
  },
  {
    slug: "mount-batur-zonsopgang",
    title: "Mount Batur: zonsopgang-trekking op de vulkaan",
    short: "Twee uur klimmen in het donker, dan de zon boven de Agung zien opkomen",
    category: "avontuur",
    region: "Kintamani",
    duration: "Nacht en ochtend (02:00 – 11:00)",
    priceFrom: 45,
    priceUnit: "pp",
    priceNote: "incl. ophalen in Ubud, lokale berggids, zaklamp en een eenvoudig ontbijt op de top",
    image: "/images/tours/mount-batur-zonsopgang.jpg",
    imageAlt: "Zonsopgang boven het Batur-meer gezien vanaf de top van de Mount Batur",
    popular: true,
    bestTime: "Droog seizoen (april – oktober) voor de grootste kans op een heldere top.",
    intro: [
      "De klim naar de top van de Mount Batur (1.717 m) is dé klassieker van Bali. Je vertrekt midden in de nacht, loopt met een hoofdlamp omhoog over vulkanisch zand en staat bij zonsopgang boven de wolken.",
      "Terwijl de zon achter de Gunung Agung en Lombok opkomt, krijg je op de top koffie en een ontbijt dat is gekookt op vulkaanstoom. Daarna wandel je door de krater terug, met uitzicht over het Batur-meer.",
    ],
    highlights: [
      "Zonsopgang op 1.717 meter boven de wolken",
      "Uitzicht over het Batur-meer en de Gunung Agung",
      "Ontbijt gestoomd in vulkanische stoomgaten",
      "Wandeling langs de kraterrand en stoomgaten",
      "Optioneel: warmwaterbronnen aan het meer na de klim",
    ],
    programma: [
      "02:00 · Ophalen in Ubud (Zuid-Bali ± 1 uur eerder)",
      "03:45 · Start van de klim met je lokale berggids",
      "05:45 · Op de top, wachten op de zonsopgang met koffie",
      "06:15 · Zonsopgang, ontbijt en foto's",
      "07:00 · Afdaling via de krater",
      "09:00 · Optioneel: Toya Devasya-warmwaterbronnen",
      "11:00 · Terug bij je verblijf",
    ],
    tips: [
      "Neem een warme laag en een windjack mee: op de top is het rond de 10 graden.",
      "Stevige schoenen met grip; het pad is los en steil.",
      "De klim duurt bijna 2 uur en is pittig maar haalbaar voor iedereen met een normale conditie.",
    ],
    inbegrepen: [
      "Ophalen en terugbrengen bij je verblijf in Ubud",
      "Lokale berggids (verplicht) en zaklamp",
      "Koffie of thee en een eenvoudig ontbijt op de top",
      "Edi als chauffeur en aanspreekpunt de hele ochtend",
    ],
    nietInbegrepen: [
      "Toegang tot de warmwaterbronnen",
      "Toeslag voor ophalen in Zuid-Bali",
      "Fooi voor de berggids",
    ],
  },
  {
    slug: "nusa-penida-west",
    title: "Nusa Penida west: Kelingking Beach, Broken Beach & Crystal Bay",
    short: "De iconische kliffen en het beroemde T-rex-strand",
    category: "strand",
    region: "Nusa Penida",
    duration: "Hele dag (± 12 uur)",
    priceFrom: 65,
    priceUnit: "pp",
    priceNote: "incl. snelle boot heen en terug en privéauto met chauffeur op het eiland",
    image: "/images/tours/nusa-penida-west.jpg",
    imageAlt: "Kelingking Beach op Nusa Penida met de klif in de vorm van een T-rex",
    popular: true,
    bestTime: "April – oktober voor kalme zee; vroeg boeken in juli en augustus.",
    intro: [
      "Nusa Penida ligt drie kwartier varen van Bali en heeft de meest spectaculaire kust van Indonesië. Vanaf het uitkijkpunt bij Kelingking kijk je neer op de kliff die de vorm van een T-rex heeft, met een strand als een poederwit lint.",
      "Edi brengt je naar de haven van Sanur, regelt de snelle boot en zorgt dat je op het eiland een eigen chauffeur hebt. Zo hoef je zelf niks te regelen en zie je in één dag de vier beroemdste plekken van de westkant.",
    ],
    highlights: [
      "Kelingking Beach en het T-rex-uitkijkpunt",
      "Angel's Billabong: natuurlijk zwembad in de rotsen",
      "Broken Beach met de natuurlijke rotsboog",
      "Crystal Bay: zwemmen en snorkelen",
      "Snelle boot vanuit Sanur, alles geregeld",
    ],
    programma: [
      "06:30 · Ophalen bij je verblijf, rit naar de haven van Sanur",
      "08:00 · Snelle boot naar Nusa Penida (± 45 min)",
      "09:00 · Kelingking Beach en uitkijkpunt",
      "11:30 · Angel's Billabong en Broken Beach",
      "13:00 · Lunch met zeezicht (eigen rekening)",
      "14:30 · Zwemmen en snorkelen bij Crystal Bay",
      "16:00 · Boot terug naar Sanur, Edi wacht in de haven",
      "18:00 · Terug bij je verblijf",
    ],
    tips: [
      "De afdaling naar Kelingking Beach zelf is steil en glibberig; het uitkijkpunt is voor de meesten genoeg.",
      "Zeeziek? Neem een tablet voor de boot; de oversteek kan onrustig zijn.",
      "Wil je in de rust van het eiland slapen? Edi stelt ook een 2-daagse variant samen.",
    ],
    inbegrepen: [
      "Ophalen en terugbrengen bij je verblijf in Zuid-Bali of Ubud",
      "Snelle boot Sanur – Nusa Penida en terug",
      "Privéauto met chauffeur op Nusa Penida",
      "Edi regelt tickets, havengeld en de planning",
    ],
    nietInbegrepen: [
      "Entreegelden op het eiland (klein bedrag per locatie)",
      "Lunch en drankjes",
      "Huur van een snorkelset (± € 3)",
    ],
  },
  {
    slug: "nusa-penida-oost",
    title: "Nusa Penida oost: Diamond Beach, Atuh Beach & Teletubbies Hills",
    short: "Rustiger dan de westkant, minstens zo mooi",
    category: "strand",
    region: "Nusa Penida",
    duration: "Hele dag (± 12 uur)",
    priceFrom: 65,
    priceUnit: "pp",
    priceNote: "incl. snelle boot heen en terug en privéauto met chauffeur op het eiland",
    image: "/images/tours/nusa-penida-oost.jpg",
    imageAlt: "Dronefoto van Diamond Beach en Atuh Beach aan de oostkust van Nusa Penida",
    bestTime: "April – oktober; bij eb is Diamond Beach het breedst.",
    intro: [
      "De oostkant van Nusa Penida is minder druk dan het westen, maar de kliffen van Diamond Beach en het uitzicht bij Atuh zijn minstens zo indrukwekkend. Denk aan turquoise water, witte rotspunten en trappen die in de klif zijn uitgehakt.",
      "Onderweg passeer je de glooiende heuvels die iedereen de Teletubbies Hills noemt en het Thousand Islands-uitkijkpunt met zijn boomhutjes. Een dag met veel wauw-momenten en weinig gedoe.",
    ],
    highlights: [
      "Diamond Beach met de trap in de klif",
      "Atuh Beach en het Raja Lima-uitkijkpunt",
      "Thousand Islands-uitkijkpunt met boomhutjes",
      "Teletubbies Hills",
      "Optioneel: Tembeling-natuurzwembad",
    ],
    programma: [
      "06:30 · Ophalen bij je verblijf, rit naar Sanur",
      "08:00 · Snelle boot naar Nusa Penida",
      "09:30 · Diamond Beach (afdaling via de trap)",
      "11:30 · Atuh Beach en Thousand Islands-uitkijkpunt",
      "13:00 · Lunch met uitzicht (eigen rekening)",
      "14:30 · Teletubbies Hills en Tembeling",
      "16:00 · Boot terug naar Sanur",
      "18:00 · Terug bij je verblijf",
    ],
    tips: [
      "De trap naar Diamond Beach is steil: goede schoenen en rustig aan.",
      "Zwemmen kan bij Diamond Beach gevaarlijk zijn door stroming; blijf dicht bij de kust.",
      "Combineer west en oost in twee dagen met een overnachting op het eiland.",
    ],
    inbegrepen: [
      "Ophalen en terugbrengen bij je verblijf in Zuid-Bali of Ubud",
      "Snelle boot Sanur – Nusa Penida en terug",
      "Privéauto met chauffeur op Nusa Penida",
      "Edi regelt tickets, havengeld en de planning",
    ],
    nietInbegrepen: [
      "Entreegelden op het eiland",
      "Lunch en drankjes",
    ],
  },
  {
    slug: "uluwatu-kecak",
    title: "Uluwatu-tempel & Kecak-vuurdans bij zonsondergang",
    short: "Tempel op de klif, apen, en honderd zingende mannen bij ondergaande zon",
    category: "tempels",
    region: "Zuid-Bali (Bukit)",
    duration: "Middag en avond (± 6 uur)",
    priceFrom: 40,
    priceUnit: "auto",
    priceNote: "Kecak-tickets ± € 9 p.p. ter plekke",
    image: "/images/tours/uluwatu-kecak.jpg",
    imageAlt: "De Uluwatu-tempel op de rand van een hoge klif boven de Indische Oceaan",
    popular: true,
    bestTime: "Het hele jaar; in het droog seizoen zie je de zon vaker echt in zee zakken.",
    intro: [
      "Pura Luhur Uluwatu balanceert op een klif van zeventig meter boven de Indische Oceaan. Het is een van de zes belangrijkste tempels van Bali en het decor van de mooiste zonsondergang van het eiland.",
      "Terwijl de zon daalt, begint in het openluchttheater de Kecak: honderd mannen die zonder instrumenten het Ramayana-epos zingen, met vuur als finale. Edi zorgt dat je op tijd bent voor een goede plek. Wie wil, sluit af met verse vis op het strand van Jimbaran.",
    ],
    highlights: [
      "Uluwatu-tempel op de klif",
      "Wandeling over het klifpad met uitzicht op de surfers",
      "Kecak-vuurdans bij zonsondergang",
      "Optioneel: Padang Padang Beach vooraf",
      "Optioneel: seafood-diner op het strand van Jimbaran",
    ],
    programma: [
      "14:00 · Ophalen bij je verblijf",
      "15:00 · Padang Padang Beach of Suluban Beach (optioneel)",
      "16:30 · Uluwatu-tempel en wandeling over het klifpad",
      "18:00 · Kecak-vuurdans terwijl de zon ondergaat",
      "19:30 · Optioneel: seafood-diner in Jimbaran",
      "21:00 · Terug bij je verblijf",
    ],
    tips: [
      "De apen bij Uluwatu zijn brutaal: bril, pet en telefoon goed vasthouden.",
      "Sarong en sjerp krijg je bij de ingang; schouders bedekt.",
      "Koop Kecak-tickets vooraf via Edi in het hoogseizoen; het theater zit vol.",
    ],
  },
  {
    slug: "tanah-lot-taman-ayun",
    title: "Tanah Lot & Taman Ayun bij zonsondergang",
    short: "De zeetempel op de rots en de koninklijke tuintempel van Mengwi",
    category: "tempels",
    region: "West- en Zuid-Bali",
    duration: "Middag (± 6 uur)",
    priceFrom: 40,
    priceUnit: "auto",
    image: "/images/tours/tanah-lot.jpg",
    imageAlt: "Zeetempel Tanah Lot op een rots in de branding",
    popular: true,
    bestTime: "Bij laag water kun je naar de rots lopen; check het tij met Edi.",
    intro: [
      "Tanah Lot is misschien wel de meest gefotografeerde tempel van Bali: een zwart rotseiland in de branding met een tempel erop. Bij zonsondergang kleurt de hemel oranje achter de tempel.",
      "Onderweg stop je bij Pura Taman Ayun, de koninklijke tempel van Mengwi met zijn meerlaagse meru-torens, omringd door een gracht en tuinen. Rustig, groen en op de UNESCO-werelderfgoedlijst.",
    ],
    highlights: [
      "Pura Taman Ayun (UNESCO) met meru-torens en gracht",
      "Tanah Lot bij laag water en bij zonsondergang",
      "Batu Bolong-tempel op de rotsboog ernaast",
      "Optioneel: Balinese kecak-dans bij Tanah Lot",
      "Optioneel: strandwandeling bij Seseh of Canggu",
    ],
    programma: [
      "13:30 · Ophalen bij je verblijf",
      "14:30 · Pura Taman Ayun in Mengwi",
      "16:00 · Aankomst Tanah Lot, wandeling langs de kust",
      "17:30 · Zonsondergang bij Tanah Lot",
      "18:30 · Terug richting je verblijf (optioneel diner onderweg)",
      "19:30 · Terug bij je verblijf",
    ],
    tips: [
      "Tanah Lot is druk bij zonsondergang; Edi kent het rustige uitzichtpunt aan de zuidkant.",
      "Bij vloed kun je niet naar de tempelrots; de zegening met heilig water is dan ook dicht.",
      "Combineer met Jatiluwih voor een volledige dag door Tabanan.",
    ],
  },
  {
    slug: "oost-bali-lempuyang",
    title: "Oost-Bali: Lempuyang 'Gates of Heaven', Tirta Gangga & Taman Ujung",
    short: "De beroemde hemelpoort met de Agung ertussen, plus twee waterpaleizen",
    category: "tempels",
    region: "Oost-Bali (Karangasem)",
    duration: "Hele dag (± 12 uur)",
    priceFrom: 65,
    priceUnit: "auto",
    image: "/images/tours/lempuyang-tirta-gangga.jpg",
    imageAlt: "De gespleten poort van de Lempuyang-tempel met wolken op de achtergrond",
    popular: true,
    bestTime: "Heel vroeg vertrekken: bij Lempuyang staat 's ochtends de kortste rij en is de Agung vaak zichtbaar.",
    intro: [
      "Oost-Bali is groener, rustiger en spectaculairder dan het zuiden. De gespleten poort van Pura Lempuyang, met de Gunung Agung precies ertussen, is de foto die iedereen wil. Edi vertrekt vroeg, zodat jullie er zijn voordat de rij lang wordt.",
      "Daarna volgen de waterpaleizen: Tirta Gangga met zijn vijvers, fonteinen en stapstenen tussen de koi, en Taman Ujung aan zee. Onderweg rijd je door rijstvelden met uitzicht op de vulkaan.",
    ],
    highlights: [
      "Pura Lempuyang en de 'Gates of Heaven'",
      "Waterpaleis Tirta Gangga",
      "Waterpaleis Taman Ujung",
      "Uitzicht op de Gunung Agung vanuit de rijstvelden",
      "Optioneel: Bukit Cinta-uitkijkpunt of het strand van Virgin Beach",
    ],
    programma: [
      "05:30 · Ophalen bij je verblijf",
      "08:00 · Pura Lempuyang, Gates of Heaven",
      "10:30 · Tirta Gangga: wandelen tussen de vijvers",
      "12:30 · Lunch met uitzicht op rijstvelden (eigen rekening)",
      "14:00 · Taman Ujung aan zee",
      "15:30 · Virgin Beach of Bukit Cinta (optioneel)",
      "18:00 · Terug bij je verblijf",
    ],
    tips: [
      "Het beroemde spiegeleffect op de foto bij Lempuyang komt van een spiegeltje onder de telefoon van de fotograaf; leuk, maar reken op wachttijd.",
      "Er rijden shuttles omhoog naar de tempel; die zijn verplicht en kosten een klein bedrag.",
      "Sarong verplicht bij Lempuyang, te huur bij de ingang.",
    ],
  },
  {
    slug: "tirta-empul-gunung-kawi",
    title: "Heilige bronnen: Tirta Empul, Gunung Kawi & Goa Gajah",
    short: "Een reinigingsritueel, koningsgraven in de rots en de olifantengrot",
    category: "tempels",
    region: "Ubud & Midden-Bali",
    duration: "Hele dag (± 8 uur)",
    priceFrom: 50,
    priceUnit: "auto",
    image: "/images/tours/tirta-empul.jpg",
    imageAlt: "Gelovigen bij de reinigingsbaden van de Tirta Empul-tempel",
    bestTime: "Het hele jaar; op volle maan en feestdagen is Tirta Empul extra sfeervol maar druk.",
    intro: [
      "Rond Tampaksiring liggen de oudste heiligdommen van Bali. In de Tirta Empul-tempel kun je meedoen aan de melukat, het reinigingsritueel waarbij je onder de dertien bronnen door gaat. Edi legt uit hoe het hoort en regelt een sarong.",
      "Bij Gunung Kawi daal je een trap van driehonderd treden af naar tien koningsgraven die in de elfde eeuw in de rotswand zijn uitgehakt. Op de terugweg bezoek je Goa Gajah, de olifantengrot uit de negende eeuw.",
    ],
    highlights: [
      "Reinigingsritueel (melukat) bij Tirta Empul",
      "Rotsgraven van Gunung Kawi",
      "Goa Gajah, de olifantengrot",
      "Rijstvelden en het dorp Tampaksiring",
      "Optioneel: koffieplantage met luwak-koffie",
    ],
    programma: [
      "08:30 · Ophalen bij je verblijf",
      "09:30 · Goa Gajah",
      "11:00 · Gunung Kawi, koningsgraven en rijstvelden",
      "12:30 · Lunch in Tampaksiring (eigen rekening)",
      "14:00 · Tirta Empul en het reinigingsritueel",
      "16:00 · Koffieplantage of terug naar Ubud",
      "17:00 · Terug bij je verblijf",
    ],
    tips: [
      "Voor het ritueel bij Tirta Empul heb je een aparte, groene sarong nodig; die krijg je bij de tempel.",
      "Neem droge kleren en een handdoek mee.",
      "Gunung Kawi vraagt een stevige klim terug; neem de tijd.",
    ],
  },
  {
    slug: "besakih-sidemen",
    title: "Moedertempel Besakih & de Sidemen-vallei",
    short: "Het grootste tempelcomplex van Bali op de flank van de Agung",
    category: "tempels",
    region: "Oost-Bali (Karangasem)",
    duration: "Hele dag (± 10 uur)",
    priceFrom: 60,
    priceUnit: "auto",
    image: "/images/tours/besakih-sidemen.jpg",
    imageAlt: "De trap en de gespleten poort van de Besakih-moedertempel",
    bestTime: "Ochtend: dan is de Agung boven de tempel het vaakst wolkenvrij.",
    intro: [
      "Pura Besakih is de 'moedertempel' van Bali: een complex van meer dan twintig tempels, duizend meter hoog op de flank van de heilige Gunung Agung. Met een lokale gids begrijp je wat je ziet, en Edi weet hoe je de opdringerige tussenpersonen ontloopt.",
      "Na de tempel daal je af naar de Sidemen-vallei, misschien wel het mooiste rijstlandschap van Bali. Hier wordt nog geweven en gewerkt op het land zoals vijftig jaar geleden.",
    ],
    highlights: [
      "Pura Besakih, de moedertempel",
      "Uitzicht op de Gunung Agung",
      "Sidemen-vallei met rijstvelden en de Unda-rivier",
      "Weefatelier voor songket en endek",
      "Optioneel: Bukit Jambul-uitkijkpunt",
    ],
    programma: [
      "07:30 · Ophalen bij je verblijf",
      "09:30 · Pura Besakih met lokale gids",
      "12:00 · Lunch met uitzicht over de Sidemen-vallei (eigen rekening)",
      "13:30 · Wandeling door de rijstvelden van Sidemen",
      "15:00 · Weefatelier en dorp",
      "16:00 · Terug via Bukit Jambul",
      "17:30 · Terug bij je verblijf",
    ],
    tips: [
      "Bij Besakih is de officiële toegang inclusief gids en shuttle; koop geen losse 'donaties' bij de poort.",
      "Op grote ceremoniedagen is de tempel deels gesloten voor bezoekers.",
      "Sidemen is ook ideaal om een nachtje te blijven; Edi haalt je de volgende dag op.",
    ],
  },
  {
    slug: "jatiluwih",
    title: "Jatiluwih UNESCO-rijstterrassen & Batukaru-tempel",
    short: "Eindeloze groene terrassen zonder drukte, met een wandeling erdoorheen",
    category: "natuur",
    region: "Midden-Bali (Tabanan)",
    duration: "Hele dag (± 9 uur)",
    priceFrom: 55,
    priceUnit: "auto",
    image: "/images/tours/jatiluwih.jpg",
    imageAlt: "Rijstterrassen van Jatiluwih met bergen op de achtergrond",
    imagePosition: "object-[50%_60%]",
    popular: true,
    bestTime: "Groen van januari tot en met april en van juli tot oktober; goudgeel vlak voor de oogst.",
    intro: [
      "Jatiluwih betekent 'echt mooi', en dat klopt. De rijstterrassen liggen hier over honderden hectares tegen de flank van de Batukaru, doorsneden door het traditionele subak-irrigatiesysteem dat op de UNESCO-lijst staat.",
      "Anders dan bij Tegallalang is het hier rustig. Je wandelt een uur of twee over de dijkjes tussen de velden, ziet boeren aan het werk en luncht met uitzicht. Daarna bezoek je de mysterieuze Batukaru-tempel in het bergwoud.",
    ],
    highlights: [
      "Jatiluwih-rijstterrassen (UNESCO-werelderfgoed)",
      "Wandelroute door de velden (5 of 8 km)",
      "Pura Luhur Batukaru in het regenwoud",
      "Uitzicht op de vulkanen Batukaru en Bratan",
      "Optioneel: Ulun Danu Beratan-tempel aan het meer",
    ],
    programma: [
      "08:00 · Ophalen bij je verblijf",
      "10:00 · Aankomst Jatiluwih, wandeling door de rijstterrassen",
      "12:30 · Lunch met uitzicht (eigen rekening)",
      "14:00 · Pura Luhur Batukaru",
      "15:30 · Optioneel: Ulun Danu Beratan-tempel",
      "17:00 · Terug bij je verblijf",
    ],
    tips: [
      "Dichte schoenen: de paadjes zijn soms modderig.",
      "Op maandag zijn de rijstvelden doorgaans het minst druk.",
      "Neem een regenjasje mee; het bergklimaat is wisselvallig.",
    ],
  },
  {
    slug: "bedugul-ulun-danu",
    title: "Bedugul: Ulun Danu Beratan, Handara Gate & de Candikuning-markt",
    short: "De tempel op het meer, de fotogenieke poort en verse aardbeien uit de bergen",
    category: "tempels",
    region: "Midden- en Noord-Bali",
    duration: "Hele dag (± 9 uur)",
    priceFrom: 55,
    priceUnit: "auto",
    image: "/images/tours/ulun-danu-beratan.jpg",
    imageAlt: "De meru-torens van de Ulun Danu Beratan-tempel aan het Bratan-meer",
    bestTime: "Ochtend: dan spiegelt de tempel in het meer en hangt er vaak nog mist.",
    intro: [
      "Op 1.200 meter hoogte is het koel en groen. De Ulun Danu Beratan-tempel lijkt op het Bratan-meer te drijven; het is de tempel van het 50.000-rupiahbiljet. In de ochtend hangt er mist en spiegelen de meru-torens in het water.",
      "Daarna rijd je langs de Handara Gate, de iconische poort met de bergen erachter, en struin je over de Candikuning-markt met aardbeien, passievrucht en specerijen uit de bergen. Botanische tuin en Bali Treetop kunnen erbij als je wilt.",
    ],
    highlights: [
      "Pura Ulun Danu Beratan op het meer",
      "Handara Gate",
      "Candikuning-markt met bergfruit en specerijen",
      "Botanische tuin van Bali (optioneel)",
      "Uitzicht over de tweelingmeren Buyan en Tamblingan",
    ],
    programma: [
      "07:30 · Ophalen bij je verblijf",
      "09:30 · Pura Ulun Danu Beratan",
      "11:00 · Handara Gate",
      "11:45 · Candikuning-markt",
      "12:30 · Lunch aan het meer (eigen rekening)",
      "14:00 · Botanische tuin of uitkijkpunt tweelingmeren",
      "16:30 · Terug bij je verblijf",
    ],
    tips: [
      "Het is hier merkbaar koeler: neem een vest mee.",
      "Bij Handara Gate betaal je voor een foto op de trap; Edi weet het gratis alternatief.",
      "Combineer met Jatiluwih of met de watervallen van Munduk.",
    ],
  },
  {
    slug: "munduk",
    title: "Munduk: tweelingmeren, Banyumala-waterval & kloofwandeling",
    short: "Koele bergdorpen, kruidnagelplantages en watervallen zonder drukte",
    category: "natuur",
    region: "Noord-Bali",
    duration: "Hele dag (± 10 uur)",
    priceFrom: 60,
    priceUnit: "auto",
    image: "/images/tours/munduk.jpg",
    imageAlt: "Waterval in het regenwoud bij Munduk",
    bestTime: "Droog seizoen voor stevige maar veilige watervallen; regenseizoen voor maximale waterkracht.",
    intro: [
      "Munduk is een bergdorp uit de Nederlandse tijd, met koloniale huizen, kruidnagelbomen en uitzicht over de tweelingmeren Buyan en Tamblingan. Het tempo ligt hier laag en de lucht is fris.",
      "Je wandelt naar de Banyumala-tweelingwaterval, waar je in een natuurlijk bassin kunt zwemmen, en volgt een kloofpad langs koffie- en kruidnagelplantages. Onderweg stop je bij het uitkijkpunt over de meren en het drijvende Wanagiri-fotopunt.",
    ],
    highlights: [
      "Banyumala-tweelingwaterval met zwembassin",
      "Uitzicht over de meren Buyan en Tamblingan",
      "Wandeling langs kruidnagel- en koffieplantages",
      "Munduk-waterval of Golden Valley",
      "Wanagiri Hidden Hills (fotopunt)",
    ],
    programma: [
      "07:30 · Ophalen bij je verblijf",
      "09:30 · Uitkijkpunt tweelingmeren en Wanagiri",
      "10:30 · Wandeling naar de Banyumala-waterval, zwemmen",
      "13:00 · Lunch in Munduk met uitzicht (eigen rekening)",
      "14:30 · Kloofwandeling langs de plantages",
      "16:00 · Terugreis via Bedugul",
      "17:30 · Terug bij je verblijf",
    ],
    tips: [
      "Waterschoenen zijn handig in de bassins; de stenen zijn glad.",
      "Neem een handdoek en droge kleren mee.",
      "Wie langer wil blijven: Munduk heeft prachtige kleine eco-lodges.",
    ],
  },
  {
    slug: "noord-bali-watervallen",
    title: "Watervallen van Noord-Bali: Gitgit, Sekumpul & Aling-Aling",
    short: "De hoogste en krachtigste watervallen van het eiland op één dag",
    category: "natuur",
    region: "Noord-Bali (Buleleng)",
    duration: "Hele dag (± 11 uur)",
    priceFrom: 65,
    priceUnit: "auto",
    image: "/images/tours/sekumpul-waterval.jpg",
    imageAlt: "Gitgit-waterval die in een groen bassin stort, omringd door regenwoud",
    bestTime: "Het hele jaar; na regen zijn de watervallen het meest indrukwekkend.",
    intro: [
      "Sekumpul wordt vaak de mooiste waterval van Bali genoemd: zeven stromen die tachtig meter naar beneden komen in een groene kloof. Je bereikt hem via een trap en een rivieroversteek, en dat maakt de aankomst extra bijzonder.",
      "Onderweg stop je bij de statige Gitgit-waterval en bij Aling-Aling, waar je van de rotsen kunt glijden en springen met een lokale gids. Een dag vol natuur, met weinig andere toeristen.",
    ],
    highlights: [
      "Sekumpul-waterval (± 80 meter hoog)",
      "Fiji-waterval, vlak naast Sekumpul",
      "Gitgit-waterval",
      "Aling-Aling: glijden en springen van de rotsen (optioneel)",
      "Uitzicht over de noordkust bij Singaraja",
    ],
    programma: [
      "07:00 · Ophalen bij je verblijf",
      "09:30 · Gitgit-waterval",
      "10:45 · Sekumpul en Fiji: trap naar beneden, rivier oversteken, zwemmen",
      "13:00 · Lunch in een warung met uitzicht (eigen rekening)",
      "14:30 · Aling-Aling (optioneel met gids voor de sprongen)",
      "16:00 · Terugreis via Bedugul",
      "18:00 · Terug bij je verblijf",
    ],
    tips: [
      "Bij Sekumpul is een lokale gids verplicht voor de volledige route; de korte route mag zonder.",
      "Draag stevige sandalen of waterschoenen; de treden zijn glad.",
      "Neem een droge tas mee voor telefoon en portemonnee.",
    ],
    nietInbegrepen: [
      "Entreegelden en lokale gids bij Sekumpul (± € 8 – 12 p.p.)",
      "Aling-Aling glij- en springpakket (± € 10 p.p.)",
      "Lunch en drankjes",
    ],
  },
  {
    slug: "watervallen-ubud",
    title: "Watervallen rond Ubud: Tegenungan, Tibumana, Kanto Lampo & Tukad Cepung",
    short: "Vier heel verschillende watervallen op een uur van Ubud",
    category: "natuur",
    region: "Ubud & Midden-Bali",
    duration: "Hele dag (± 8 uur)",
    priceFrom: 50,
    priceUnit: "auto",
    image: "/images/tours/watervallen-ubud.jpg",
    imageAlt: "De Tegenungan-waterval omringd door jungle",
    popular: true,
    bestTime: "Tukad Cepung in de ochtend (10:00 – 12:00) voor de lichtstralen in de grot.",
    intro: [
      "Rond Ubud liggen tientallen watervallen, elk met een eigen karakter. Tukad Cepung stort in een grot waar het zonlicht in stralen naar binnen valt. Kanto Lampo glijdt breed over een rotsformatie waar je onder kunt staan.",
      "Tibumana is een klassieke, rechte waterval met een bassin om in te zwemmen, en Tegenungan is de grootste en meest bekende. Edi plant de volgorde op het licht en de drukte, zodat je elke plek op z'n mooist ziet.",
    ],
    highlights: [
      "Tukad Cepung met lichtstralen in de grot",
      "Kanto Lampo, de brede waterval over de rotsen",
      "Tibumana met zwembassin",
      "Tegenungan-waterval",
      "Optioneel: Goa Rang Reng of Suwat",
    ],
    programma: [
      "08:00 · Ophalen bij je verblijf",
      "09:30 · Tukad Cepung",
      "11:00 · Tibumana, zwemmen",
      "12:30 · Lunch in een warung (eigen rekening)",
      "14:00 · Kanto Lampo",
      "15:30 · Tegenungan",
      "16:30 · Terug bij je verblijf",
    ],
    tips: [
      "Waterschoenen en een handdoek maken de dag veel comfortabeler.",
      "Bij Tukad Cepung loop je door een beekje; broek oprollen.",
      "Na hevige regen kan het water bruin en snel zijn; Edi kiest dan andere watervallen.",
    ],
  },
  {
    slug: "bali-swing",
    title: "Bali Swing, Tegallalang & koffieplantage",
    short: "Zweven boven de jungle, met de rijstterrassen als decor",
    category: "avontuur",
    region: "Ubud & Midden-Bali",
    duration: "Halve dag (± 5 uur)",
    priceFrom: 40,
    priceUnit: "auto",
    priceNote: "swing-tickets ± € 20 – 35 p.p. ter plekke, afhankelijk van het park",
    image: "/images/tours/bali-swing.jpg",
    imageAlt: "Vrouw in rode jurk op een reuzenschommel boven de jungle bij Ubud",
    bestTime: "Ochtend voor het zachtste licht en de kortste rijen.",
    intro: [
      "De reuzenschommels van Bali zijn een fenomeen geworden: aan touwen van tien tot twintig meter zweef je boven een groene kloof of over de rijstterrassen. Doodeng, doodleuk en een ongelooflijke foto.",
      "Edi kent de parken bij Tegallalang en Bongkasa en weet welke bij jullie past: van de grote parken met fotografen en jurken tot de kleine schommel van een boer aan de rand van zijn rijstveld. Daarna proef je koffie op een plantage.",
    ],
    highlights: [
      "Reuzenschommel boven de jungle of rijstterrassen",
      "Fotomomenten in nesten en op het 'vogelnest'-platform",
      "Rijstterrassen van Tegallalang",
      "Koffieplantage met proeverij",
      "Optioneel: Tegenungan-waterval",
    ],
    programma: [
      "08:00 · Ophalen bij je verblijf",
      "09:00 · Swing-park: schommelen en foto's",
      "11:00 · Rijstterrassen van Tegallalang",
      "12:00 · Koffieplantage",
      "13:00 · Terug bij je verblijf (of doorrijden naar Ubud)",
    ],
    tips: [
      "Een wijde jurk of rok levert de mooiste foto's; bij veel parken te huur.",
      "Er is een veiligheidsharnas; de grote schommels zijn niet geschikt voor kleine kinderen.",
      "Wil je een rustige, kleine schommel? Zeg het Edi.",
    ],
  },
  {
    slug: "rafting-ayung",
    title: "Wildwaterraften op de Ayung-rivier",
    short: "Twee uur stroomversnellingen door de jungle, met watervallen langs de route",
    category: "avontuur",
    region: "Ubud & Midden-Bali",
    duration: "Halve dag (± 5 uur)",
    priceFrom: 35,
    priceUnit: "pp",
    priceNote: "incl. uitrusting, gids op de boot, douches en lunch; ophalen in Ubud inbegrepen",
    image: "/images/tours/rafting-ayung.jpg",
    imageAlt: "Raft met peddelaars in helmen en zwemvesten op de Ayung-rivier",
    bestTime: "Het hele jaar; in het regenseizoen is de rivier wilder.",
    intro: [
      "De Ayung is de langste rivier van Bali en slingert zich door een diepe, groene kloof onder Ubud. Twaalf kilometer lang peddel je door stroomversnellingen (klasse II en III), onder watervallen door en langs rotsreliëfs van het Ramayana.",
      "De gidsen zijn ervaren en de tocht is geschikt voor iedereen vanaf ongeveer 7 jaar. Na afloop douche je, krijg je een Indonesisch buffet en brengt Edi je terug.",
    ],
    highlights: [
      "12 km raften met stroomversnellingen klasse II en III",
      "Watervallen en rotsreliëfs langs de route",
      "Jungle-kloof onder de luxe resorts van Ubud",
      "Lunchbuffet met uitzicht na afloop",
      "Optioneel: combineren met de Bali Swing in de middag",
    ],
    programma: [
      "08:00 · Ophalen bij je verblijf",
      "09:00 · Briefing en uitrusting bij het startpunt",
      "09:30 · Raften (± 2 uur)",
      "11:30 · Douchen en lunchbuffet",
      "13:00 · Terug bij je verblijf",
    ],
    tips: [
      "Draag zwemkleding en schoenen die nat mogen worden.",
      "Waterdichte hoes voor je telefoon, of geef hem aan de gids in de droge tas.",
      "Het start- en eindpunt hebben honderden treden; houd hier rekening mee.",
    ],
    inbegrepen: [
      "Ophalen en terugbrengen in Ubud (Zuid-Bali tegen toeslag)",
      "Raft, helm, zwemvest en peddel",
      "Ervaren riviergids",
      "Douches, handdoeken en lunchbuffet",
    ],
    nietInbegrepen: [
      "Foto's van de fotografen langs de route",
      "Drankjes bij de lunch",
      "Fooi voor de riviergids",
    ],
  },
  {
    slug: "atv-quad",
    title: "ATV-quadtour door rijstvelden, jungle en rivierbedding",
    short: "Modder, tunnels en watervallen op een quad, met een gids voorop",
    category: "avontuur",
    region: "Ubud (Payangan)",
    duration: "Halve dag (± 4 uur)",
    priceFrom: 45,
    priceUnit: "pp",
    priceNote: "incl. quad (single), helm, instructie, gids en lunch; tandem goedkoper per persoon",
    image: "/images/tours/atv-quad.jpg",
    imageAlt: "Twee quads rijden over een veld met bergen op de achtergrond",
    bestTime: "Het hele jaar; na regen is het parcours het meest modderig en het meest leuk.",
    intro: [
      "Op een quad kom je op plekken waar geen auto kan: smalle paadjes tussen rijstvelden, een oude waterval-tunnel, rivierbeddingen en modderpoelen. Een gids rijdt voorop en past het tempo aan.",
      "Je hoeft geen ervaring te hebben; na tien minuten oefenen op het terrein ga je het veld in. Reken op anderhalf tot twee uur rijden en op modder tot aan je oren.",
    ],
    highlights: [
      "Rijden door rijstvelden, jungle en een rivierbedding",
      "Tunnel en waterval-doorsteek",
      "Panorama over de kloof van de Ayung",
      "Instructie en gids voorop",
      "Douche en lunch na afloop",
    ],
    programma: [
      "08:30 · Ophalen bij je verblijf",
      "09:30 · Instructie en oefenronde",
      "10:00 · Quadtour (± 2 uur)",
      "12:00 · Douchen en lunch",
      "13:00 · Terug bij je verblijf",
    ],
    tips: [
      "Trek kleding aan die vies mag worden; schoenen krijg je meestal ter plekke.",
      "Kinderen vanaf ongeveer 8 jaar kunnen achterop bij een ouder.",
      "Combineer met raften voor een volledige avonturendag.",
    ],
    inbegrepen: [
      "Ophalen en terugbrengen in Ubud (Zuid-Bali tegen toeslag)",
      "Quad, helm, laarzen en instructie",
      "Gids voorop tijdens de hele tour",
      "Douche, handdoek en lunch",
    ],
    nietInbegrepen: ["Foto's en video's van het park", "Fooi voor de gids"],
  },
  {
    slug: "snorkelen-blue-lagoon",
    title: "Snorkelen bij Blue Lagoon & Padangbai",
    short: "Kleurrijk koraal en schildpadden op een rustige oostkust",
    category: "strand",
    region: "Oost-Bali (Padangbai)",
    duration: "Hele dag (± 8 uur)",
    priceFrom: 55,
    priceUnit: "auto",
    priceNote: "traditionele boot met snorkelset ± € 25 p.p., te regelen via Edi",
    image: "/images/tours/snorkelen-padangbai.jpg",
    imageAlt: "Traditionele jukung-boten op turquoise water bij Padangbai",
    bestTime: "Ochtend voor het helderste water; april – november voor de kalmste zee.",
    intro: [
      "Blue Lagoon is een kleine baai bij het havendorp Padangbai met een van de mooiste koraalriffen die je vanaf het strand kunt bereiken. Vanaf een traditionele jukung-boot snorkel je boven koraal vol clownvissen, koraalduivels en met een beetje geluk een zeeschildpad.",
      "Daarna kun je uitrusten op het witte strand van Bias Tugel of een tweede snorkelspot bezoeken. Onderweg vanuit het zuiden kun je stoppen bij Goa Lawah, de vleermuizengrot-tempel.",
    ],
    highlights: [
      "Snorkelen bij Blue Lagoon en Tanjung Jepun",
      "Traditionele jukung-boot met schipper",
      "Strand van Bias Tugel",
      "Pura Goa Lawah, de vleermuizentempel",
      "Vis-lunch aan de haven van Padangbai",
    ],
    programma: [
      "07:30 · Ophalen bij je verblijf",
      "09:00 · Pura Goa Lawah",
      "10:00 · Snorkelen bij Blue Lagoon (2 spots, ± 2 uur)",
      "12:30 · Lunch aan de haven (eigen rekening)",
      "14:00 · Strand Bias Tugel of tweede snorkelronde",
      "15:30 · Terug bij je verblijf",
    ],
    tips: [
      "Watervast zonnebrand of een UV-shirt; op het water verbrand je snel.",
      "Eigen snorkelmasker mee als je er een hebt; de huursets zijn eenvoudig.",
      "Blue Lagoon is ook ideaal voor een eerste duik (Discover Scuba) via een lokale duikschool.",
    ],
  },
  {
    slug: "manta-point",
    title: "Snorkelen met manta's rond Nusa Penida",
    short: "Reuzenmanta's, kristalhelder water en drie tot vier snorkelspots op één dag",
    category: "strand",
    region: "Nusa Penida",
    duration: "Hele dag (± 9 uur)",
    priceFrom: 55,
    priceUnit: "pp",
    priceNote: "incl. snelle boot vanaf Sanur, 3 – 4 snorkelspots, snorkelset, gids op de boot en lunch",
    image: "/images/tours/manta-point.jpg",
    imageAlt: "Reuzenmanta zwemt onder water bij Manta Point, Nusa Penida",
    popular: true,
    bestTime: "Het hele jaar; de manta's zijn er altijd, het zicht is het best van april tot november.",
    intro: [
      "Bij Manta Point aan de zuidkust van Nusa Penida komen reuzenmanta's zich laten schoonmaken bij het rif. Met een spanwijdte tot vier meter zweven ze onder je door, en dat vergeet je nooit meer.",
      "Vanaf Sanur ga je met een snelle boot naar drie of vier snorkelspots: Manta Point, Crystal Bay, Gamat Bay en de wand van Nusa Lembongan waar je koraal in alle kleuren ziet. Edi brengt je naar de haven en staat er weer als je terugkomt.",
    ],
    highlights: [
      "Manta Point: snorkelen met reuzenmanta's",
      "Crystal Bay en Gamat Bay",
      "Koraaltuin bij Nusa Lembongan",
      "Snelle boot met gids en snorkelset",
      "Lunch op Lembongan of aan boord",
    ],
    programma: [
      "07:00 · Ophalen bij je verblijf",
      "08:00 · Vertrek snelle boot vanuit Sanur",
      "09:00 · Snorkelen bij Manta Point",
      "10:30 · Crystal Bay en Gamat Bay",
      "12:30 · Lunch",
      "13:30 · Koraaltuin Lembongan",
      "15:00 · Terug naar Sanur, Edi wacht in de haven",
      "16:00 · Terug bij je verblijf",
    ],
    tips: [
      "Manta Point kan onrustig water hebben; luister naar de gids en blijf rustig aan de oppervlakte.",
      "Raak de manta's nooit aan en zwem niet boven ze: houd afstand, dan blijven ze langer.",
      "Neem een UV-shirt of wetsuit-shirt mee tegen zon en kou.",
    ],
    inbegrepen: [
      "Ophalen en terugbrengen bij je verblijf in Zuid-Bali of Ubud",
      "Snelle boot met ervaren schipper en snorkelgids",
      "Snorkelset en zwemvest",
      "Lunch, water en fruit",
    ],
    nietInbegrepen: ["Huur van vinnen of wetsuit", "Onderwaterfoto's van de gids", "Fooi voor de bemanning"],
  },
  {
    slug: "menjangan",
    title: "Menjangan-eiland: snorkelen in het West-Bali Nationaal Park",
    short: "De beste koraalwanden van Bali, in het stilste stukje van het eiland",
    category: "strand",
    region: "West-Bali",
    duration: "Hele dag (± 13 uur)",
    priceFrom: 75,
    priceUnit: "pp",
    priceNote: "incl. privéauto, boot naar Menjangan, snorkelset, parkgids en nationaal-parkbijdrage",
    image: "/images/tours/menjangan.jpg",
    imageAlt: "Strand met koraalrif en donkere wolken bij het Menjangan-eiland",
    bestTime: "April – november; de lange rit loont het meest met een hele dag zon.",
    intro: [
      "Menjangan ligt aan de noordwestpunt van Bali in het West-Bali Nationaal Park en heeft de beste snorkel- en duikwanden van het eiland: verticale koraalmuren, zicht tot dertig meter en vrijwel geen stroming.",
      "Het is een lange rit, maar Edi maakt er een mooie dag van met een stop in het bergdorp Pupuan of langs de noordkust. Op het eiland leven herten en zeearenden; onder water zwem je tussen scholen doktersvissen en koraalgrotten.",
    ],
    highlights: [
      "Koraalwanden van Menjangan (Eel Garden, Pos II)",
      "West-Bali Nationaal Park met herten en zeearenden",
      "Kristalhelder water zonder stroming",
      "Rit door de rijstvelden en plantages van Pupuan",
      "Optioneel: overnachting in Pemuteran",
    ],
    programma: [
      "05:30 · Ophalen bij je verblijf",
      "08:30 · Ontbijtstop in Pupuan of aan de noordkust",
      "10:00 · Boot vanuit Labuhan Lalang naar Menjangan",
      "10:30 · Snorkelen op 2 – 3 spots",
      "13:30 · Lunch op het eiland of in Pemuteran",
      "15:00 · Terugreis via de kustweg",
      "18:30 · Terug bij je verblijf",
    ],
    tips: [
      "Maak er twee dagen van met een nacht in Pemuteran: rustig dorp, mooie duikscholen.",
      "Het is een lange autodag; ideaal om te combineren met Lovina op de terugweg.",
      "Neem een UV-shirt mee: op de boot is weinig schaduw.",
    ],
    inbegrepen: [
      "Privéauto met Edi, ophalen en terugbrengen",
      "Boot naar Menjangan met schipper en parkgids",
      "Snorkelset en zwemvest",
      "Bijdrage aan het nationaal park",
    ],
    nietInbegrepen: ["Maaltijden en drankjes", "Fooien"],
  },
  {
    slug: "lovina-dolfijnen",
    title: "Lovina: dolfijnen bij zonsopgang, Banjar-warmwaterbronnen & boeddhistische tempel",
    short: "Wilde dolfijnen vanaf een houten bootje, daarna ontspannen in het warme water",
    category: "natuur",
    region: "Noord-Bali (Buleleng)",
    duration: "Vroege ochtend (± 10 uur)",
    priceFrom: 65,
    priceUnit: "auto",
    priceNote: "dolfijnenboot ± € 12 p.p.",
    image: "/images/tours/lovina-dolfijnen.jpg",
    imageAlt: "Dolfijnen springen uit het water voor de kust van Lovina, met een bootje op de achtergrond",
    imagePosition: "object-[50%_45%]",
    bestTime: "Het hele jaar; vertrek altijd voor zonsopgang, dan zijn de dolfijnen het actiefst.",
    intro: [
      "Voor de kust van Lovina leven honderden dolfijnen die bij zonsopgang komen jagen. Vanaf een traditionele jukung, met de zon die achter de bergen opkomt, zie je ze om je heen springen.",
      "Terug op het land wacht Brahmavihara-Arama, het grootste boeddhistische klooster van Bali met een kleine Borobudur, en de warmwaterbronnen van Banjar, waar je uit de bek van stenen draken in het warme, zwavelhoudende water stapt.",
    ],
    highlights: [
      "Dolfijnen spotten bij zonsopgang vanaf een jukung",
      "Zwart zandstrand van Lovina",
      "Boeddhistisch klooster Brahmavihara-Arama",
      "Warmwaterbronnen van Banjar",
      "Optioneel: Gitgit-waterval op de terugweg",
    ],
    programma: [
      "03:30 · Ophalen bij je verblijf (vanuit Ubud; Zuid-Bali eerder)",
      "06:00 · Boottocht met dolfijnen bij zonsopgang (± 1,5 uur)",
      "08:00 · Ontbijt aan het strand (eigen rekening)",
      "09:30 · Brahmavihara-Arama",
      "10:30 · Warmwaterbronnen van Banjar",
      "12:30 · Lunch en terugreis via Bedugul",
      "14:30 · Terug bij je verblijf",
    ],
    tips: [
      "Slaap een nacht in Lovina als je niet midden in de nacht wilt vertrekken; Edi haalt je ter plaatse op.",
      "Er zijn veel bootjes bij de dolfijnen; kies via Edi een schipper die afstand houdt.",
      "Zwemkleding en handdoek voor de warmwaterbronnen.",
    ],
  },
  {
    slug: "amed-tulamben",
    title: "Amed & Tulamben: snorkelen bij het USAT Liberty-scheepswrak",
    short: "Een scheepswrak op dertig meter van het strand, en vissersdorpen aan de voet van de Agung",
    category: "strand",
    region: "Oost-Bali (Karangasem)",
    duration: "Hele dag (± 10 uur)",
    priceFrom: 60,
    priceUnit: "auto",
    priceNote: "snorkelset te huur op het strand (± € 3), duikschool regelt Edi op verzoek",
    image: "/images/tours/amed-tulamben.jpg",
    imageAlt: "Baai van Amed bij zonsondergang met de Gunung Agung op de achtergrond",
    imagePosition: "object-[50%_55%]",
    bestTime: "Ochtend: het rustigste water bij het wrak is voor 10:00 uur.",
    intro: [
      "In 1942 werd het Amerikaanse vrachtschip USAT Liberty getorpedeerd en op het strand van Tulamben gezet; in 1963 duwde de uitbarsting van de Agung het de zee in. Nu ligt het wrak van 120 meter op maar dertig meter van het strand, begroeid met koraal en vol vissen. Snorkelend zie je het bovenste deel al.",
      "Amed, iets verderop, is een reeks vissersbaaien met zwart zand, jukungs op het strand en de Gunung Agung als achtergrond. Bij de Japanse wrak-snorkelspot en de Jemeluk-baai is het rif direct vanaf het strand te bereiken.",
    ],
    highlights: [
      "Snorkelen boven het USAT Liberty-wrak",
      "Jemeluk-baai en het Japanse scheepswrak bij Amed",
      "Vissersdorpen met traditionele jukungs",
      "Uitzicht op de Gunung Agung vanaf de kust",
      "Optioneel: Tirta Gangga onderweg",
    ],
    programma: [
      "06:30 · Ophalen bij je verblijf",
      "09:00 · Snorkelen bij het Liberty-wrak in Tulamben",
      "11:00 · Rit langs de kust naar Amed",
      "12:00 · Lunch met zeezicht in Jemeluk (eigen rekening)",
      "13:30 · Snorkelen in de Jemeluk-baai of bij het Japanse wrak",
      "15:00 · Uitkijkpunt Amed en terugreis (optioneel via Tirta Gangga)",
      "17:00 · Terug bij je verblijf",
    ],
    tips: [
      "Het wrak begint op 5 meter diepte; met een goed masker zie je veel, met een duikles nog meer.",
      "Neem watervaste sandalen mee: het strand van Tulamben bestaat uit grote kiezels.",
      "Blijf een nacht in Amed voor de zonsopgang boven Lombok.",
    ],
  },
  {
    slug: "kintamani-penglipuran",
    title: "Kintamani-vulkaanuitzicht, Penglipuran-dorp & luwak-koffie",
    short: "Uitzicht op de Batur, het schoonste dorp van Bali en koffie met een verhaal",
    category: "natuur",
    region: "Kintamani & Bangli",
    duration: "Hele dag (± 9 uur)",
    priceFrom: 55,
    priceUnit: "auto",
    image: "/images/tours/kintamani-koffie.jpg",
    imageAlt: "Uitzicht op de Mount Batur en het Batur-meer vanaf Kintamani",
    popular: true,
    bestTime: "Ochtend, voordat de wolken rond de Batur komen.",
    intro: [
      "Vanaf de kraterrand bij Kintamani kijk je uit over de Mount Batur, zijn zwarte lavavelden en het grote kratermeer. Een van de weidste uitzichten van Bali, het liefst bij een kop koffie op een terras.",
      "Op de terugweg bezoek je Penglipuran, een traditioneel Bali Aga-dorp dat bekendstaat als een van de schoonste dorpen ter wereld, en een koffieplantage waar je ziet hoe kopi luwak wordt gemaakt en waar je twaalf soorten koffie en thee kunt proeven.",
    ],
    highlights: [
      "Uitzicht op de Mount Batur en het Batur-meer",
      "Traditioneel dorp Penglipuran met bamboebos",
      "Koffieplantage en proeverij (kopi luwak optioneel)",
      "Pura Kehen, de tempel van Bangli",
      "Optioneel: Tegallalang op de terugweg",
    ],
    programma: [
      "08:00 · Ophalen bij je verblijf",
      "10:00 · Kintamani: koffie met uitzicht op de vulkaan",
      "11:30 · Wandeling door Penglipuran en het bamboebos",
      "13:00 · Lunch met uitzicht (eigen rekening)",
      "14:30 · Pura Kehen",
      "15:30 · Koffieplantage en proeverij",
      "17:00 · Terug bij je verblijf",
    ],
    tips: [
      "Op 1.500 meter is het fris; neem een vest mee.",
      "Bij de koffieplantage zijn de proefsets gratis; kopi luwak betaal je apart.",
      "In Penglipuran mag je de erven bezoeken; vraag even, en koop iets bij de bewoners.",
    ],
  },
  {
    slug: "surfles-canggu",
    title: "Surfles in Canggu & zonsondergang bij een beachclub",
    short: "Op je eerste golf staan, en dan met een drankje de zon in zee zien zakken",
    category: "avontuur",
    region: "Zuid-Bali (Canggu)",
    duration: "Middag (± 6 uur)",
    priceFrom: 35,
    priceUnit: "pp",
    priceNote: "incl. 2 uur les met instructeur, board en rashguard; auto met Edi vanaf € 35 per auto",
    image: "/images/tours/canggu-surf.jpg",
    imageAlt: "Zonsondergang op het strand van Canggu met mensen langs de vloedlijn",
    bestTime: "Mei – september voor de beste, meest constante golven.",
    intro: [
      "Canggu en Seminyak zijn perfect om te leren surfen: zandbodem, lange beginnersgolven en tientallen surfscholen. In twee uur leer je peddelen, opstaan en je eerste golf pakken.",
      "Na de les spoel je af en installeer je je bij een beachclub voor de zonsondergang, terwijl Edi de auto regelt en je later weer thuisbrengt. Een ontspannen middag met strandsfeer.",
    ],
    highlights: [
      "Surfles van 2 uur met ervaren instructeur",
      "Batu Bolong- of Berawa-strand",
      "Zonsondergang bij een beachclub in Canggu of Seminyak",
      "Optioneel: Tanah Lot vooraf",
      "Optioneel: seafood-diner in Jimbaran",
    ],
    programma: [
      "13:30 · Ophalen bij je verblijf",
      "14:30 · Surfles (theorie op het strand, dan het water in)",
      "16:30 · Douchen en omkleden",
      "17:00 · Beachclub, zonsondergang",
      "19:30 · Terug bij je verblijf",
    ],
    tips: [
      "Zonnebrand en een rashguard (krijg je van de surfschool) tegen schaafwonden.",
      "Een dag na de les heb je spierpijn in armen en schouders; normaal.",
      "Kinderen kunnen vanaf ongeveer 6 jaar mee in een aparte les.",
    ],
    inbegrepen: [
      "Surfles van 2 uur met gecertificeerde instructeur",
      "Board, rashguard en verzekering van de surfschool",
      "Edi als chauffeur (per auto)",
    ],
    nietInbegrepen: ["Drankjes en eten bij de beachclub", "Zonnebedden bij sommige clubs"],
  },
  {
    slug: "kookworkshop",
    title: "Balinese kookworkshop met marktbezoek",
    short: "Eerst de markt, dan zelf sate lilit, sambal en lawar maken",
    category: "tempels",
    region: "Ubud",
    duration: "Ochtend (± 5 uur)",
    priceFrom: 35,
    priceUnit: "pp",
    priceNote: "incl. marktbezoek, alle ingrediënten, receptenboekje en de lunch die je zelf kookt",
    image: "/images/tours/kookworkshop.jpg",
    imageAlt: "Bord nasi campur met rijst, groenten, sate en sambal",
    bestTime: "Het hele jaar; de markt is het levendigst voor 09:00 uur.",
    intro: [
      "De Balinese keuken is een van de meest onderschatte van Azië: geurige basa gede (kruidenpasta), sate lilit van gemalen vis met citroengras, lawar van jonge kokos en tempeh in zoete sojasaus. In deze workshop leer je het zelf maken.",
      "Je begint op de ochtendmarkt, waar de kokkin uitlegt wat je ziet en wat het doet. Daarna kook je in een open Balinese keuken zes tot acht gerechten en eet je ze samen op.",
    ],
    highlights: [
      "Ochtendmarkt van Ubud of Gianyar",
      "Basa gede, de Balinese basiskruidenpasta",
      "Sate lilit, lawar, pepes ikan en tempeh manis",
      "Lunch van je eigen gerechten in een open keuken",
      "Receptenboekje om thuis verder te koken",
    ],
    programma: [
      "07:30 · Ophalen bij je verblijf",
      "08:00 · Marktbezoek met de kok",
      "09:00 · Welkom, koffie en uitleg over de ingrediënten",
      "09:30 · Koken (± 3 uur)",
      "12:30 · Samen eten",
      "13:00 · Terug bij je verblijf of doorrijden naar Ubud",
    ],
    tips: [
      "Vegetarisch of veganistisch kan prima; geef het vooraf door.",
      "Ook leuk met kinderen vanaf ongeveer 8 jaar.",
      "Combineer met een middag Ubud (Monkey Forest, markt) met Edi.",
    ],
    inbegrepen: [
      "Ophalen en terugbrengen in Ubud",
      "Marktbezoek en alle ingrediënten",
      "Schort, receptenboekje en lunch",
    ],
    nietInbegrepen: ["Extra drankjes", "Fooi voor de kok"],
  },
  {
    slug: "gili-trawangan",
    title: "Dagtrip naar de Gili-eilanden",
    short: "Wit zand, schildpadden en geen auto's, op anderhalf uur varen van Bali",
    category: "strand",
    region: "Lombok / Gili-eilanden",
    duration: "Hele dag (± 13 uur)",
    priceFrom: 85,
    priceUnit: "pp",
    priceNote: "incl. transfer naar Padangbai en snelle boot heen en terug; overnachting op de Gili's mogelijk",
    image: "/images/tours/gili-trawangan.jpg",
    imageAlt: "Wit strand met turquoise water op Gili Trawangan",
    bestTime: "April – oktober; bij ruwe zee wordt de oversteek wel eens geannuleerd.",
    intro: [
      "De drie Gili-eilanden voor de kust van Lombok zijn wat veel mensen zich bij 'Bali' voorstellen: wit zand, glashelder water, geen auto's en zeeschildpadden op een paar meter van het strand.",
      "Vanuit Padangbai ben je er met de snelle boot in anderhalf tot twee uur. Op Gili Trawangan of het rustigere Gili Air huur je een fiets of snorkel je direct vanaf het strand. Edi brengt je naar de haven en haalt je 's avonds weer op, of een paar dagen later.",
    ],
    highlights: [
      "Gili Trawangan of Gili Air",
      "Snorkelen met zeeschildpadden vanaf het strand",
      "Fietsen rond het eiland zonder verkeer",
      "Zonsondergang met uitzicht op de Agung (vanaf de westkant van Gili T)",
      "Optioneel: overnachting en ophalen op een latere dag",
    ],
    programma: [
      "06:30 · Ophalen bij je verblijf",
      "08:00 · Inchecken snelle boot in Padangbai",
      "08:45 · Oversteek naar de Gili's (± 1,5 – 2 uur)",
      "10:45 · Vrije tijd: snorkelen, fietsen, strand",
      "15:30 · Boot terug naar Padangbai",
      "17:30 · Edi wacht in de haven",
      "19:00 · Terug bij je verblijf",
    ],
    tips: [
      "Een dagtrip is kort; met één of twee nachten op de Gili's komt het eiland pas echt tot z'n recht.",
      "Neem contant geld mee; geldautomaten op de Gili's zijn beperkt.",
      "Vertrektijden van de boten wisselen per seizoen; Edi checkt ze de dag ervoor.",
    ],
    inbegrepen: [
      "Ophalen en terugbrengen bij je verblijf",
      "Snelle boot Padangbai – Gili en terug",
      "Havengeld en tickets geregeld door Edi",
    ],
    nietInbegrepen: ["Maaltijden en drankjes", "Snorkelset en fietshuur op het eiland", "Overnachting"],
  },
  {
    slug: "bali-safari",
    title: "Bali Safari & Marine Park",
    short: "Safari-truck tussen zebra's en Sumatraanse tijgers, plus shows en een waterpark",
    category: "familie",
    region: "Gianyar (Zuid-Bali)",
    duration: "Hele dag (± 7 uur)",
    priceFrom: 45,
    priceUnit: "pp",
    priceNote: "Jungle Hopper-dagticket; auto met Edi vanaf € 40 per auto; kinderen goedkoper",
    image: "/images/tours/bali-safari.jpg",
    imageAlt: "Neushoorn in het Bali Safari & Marine Park",
    bestTime: "Het hele jaar; op weekdagen is het rustiger.",
    intro: [
      "Bali Safari & Marine Park is de leukste dagbesteding voor gezinnen aan de oostkant van Sanur. Vanuit een open safaritruck rijd je tussen zebra's, neushoorns, olifanten en de zeldzame Sumatraanse tijgers, in een groot park dat zich richt op behoud en fokprogramma's.",
      "Daarnaast zijn er dierenshows, een waterpark en de Bali Agung-theatershow met traditionele dans en dieren. Edi brengt je en blijft in de buurt, zodat je precies zo lang kunt blijven als de kinderen leuk vinden.",
    ],
    highlights: [
      "Safari Journey met open truck tussen de dieren",
      "Sumatraanse tijgers, olifanten en komodovaranen",
      "Dierenpresentaties en Bali Agung-show",
      "Waterpark en speeltuin voor kinderen",
      "Optioneel: ontbijt met de olifanten of Night Safari",
    ],
    programma: [
      "08:30 · Ophalen bij je verblijf",
      "09:30 · Aankomst, Safari Journey",
      "11:00 · Dierenpresentaties en Bali Agung-show",
      "13:00 · Lunch in het park (eigen rekening)",
      "14:00 · Waterpark en speeltuin",
      "15:30 · Terug bij je verblijf",
    ],
    tips: [
      "Boek tickets vooraf via Edi; dat is goedkoper dan aan de kassa.",
      "Zwemkleding mee voor het waterpark.",
      "Combineer met het Bali Bird Park voor een tweedaags familieprogramma.",
    ],
    inbegrepen: ["Jungle Hopper-dagticket", "Edi als chauffeur (per auto)"],
    nietInbegrepen: ["Maaltijden en drankjes", "Optionele extra's zoals de Night Safari"],
  },
  {
    slug: "waterbom",
    title: "Waterbom Bali in Kuta",
    short: "Het beste waterpark van Azië, met glijbanen voor durfals én kleintjes",
    category: "familie",
    region: "Zuid-Bali (Kuta)",
    duration: "Hele dag (± 7 uur)",
    priceFrom: 35,
    priceUnit: "pp",
    priceNote: "dagticket; auto met Edi vanaf € 30 per auto; kinderen goedkoper",
    image: "/images/tours/waterbom.jpg",
    imageAlt: "Gasten glijden op een gele band door een glijbaan in Waterbom Bali",
    bestTime: "Het hele jaar; kom bij opening, dan zijn de rijen kort.",
    intro: [
      "Waterbom Bali in Kuta wordt jaar na jaar tot beste waterpark van Azië gekozen. Tussen tropische tuinen liggen meer dan twintig glijbanen: van de Climax met valluik en de Smashdown tot rustige lazy rivers en een kinderzone.",
      "Ideaal voor een dag ontspanning na een paar tourdagen. Edi brengt je erheen, regelt tickets en haalt je op wanneer jullie klaar zijn, ook als dat vroeger of later is dan gepland.",
    ],
    highlights: [
      "Meer dan 20 glijbanen, van extreem tot rustig",
      "Lazy river en kinderzone",
      "Tropische tuinen met ligbedden en cabana's",
      "Restaurants en cafés in het park",
      "Optioneel: zonsondergang op het strand van Kuta erna",
    ],
    programma: [
      "09:00 · Ophalen bij je verblijf",
      "10:00 · Opening Waterbom, direct naar de populairste glijbanen",
      "13:00 · Lunch in het park (eigen rekening)",
      "16:00 · Ophalen door Edi (tijd naar wens)",
      "16:30 · Optioneel: strand van Kuta",
      "17:30 · Terug bij je verblijf",
    ],
    tips: [
      "Sluit een kluisje af voor je spullen; betalen kan in het park met een polsband.",
      "Zonnebrand: je bent de hele dag in de zon en het water.",
      "Sommige glijbanen hebben een minimumlengte van 1,10 m.",
    ],
    inbegrepen: ["Dagticket Waterbom Bali", "Edi als chauffeur (per auto)"],
    nietInbegrepen: ["Kluisje, handdoeken en cabana", "Maaltijden en drankjes"],
  },
  {
    slug: "campuhan-ridge",
    title: "Ubud te voet: Campuhan Ridge Walk & dorpsleven",
    short: "Ochtendwandeling over de groene heuvelkam, dan de tempels en warungs van Ubud",
    category: "natuur",
    region: "Ubud",
    duration: "Ochtend (± 5 uur)",
    priceFrom: 40,
    priceUnit: "auto",
    image: "/images/tours/campuhan-ridge.jpg",
    imageAlt: "Het pad over de Campuhan-heuvelkam met een enkele palm en hoog gras",
    bestTime: "Voor 08:00 uur, als het nog koel is en het licht laag staat.",
    intro: [
      "De Campuhan Ridge Walk is een pad over een smalle heuvelkam tussen twee rivieren, met hoog gras, palmen en uitzicht op de rijstvelden. Twee kilometer heen en twee terug, ideaal als koele ochtendwandeling.",
      "Daarna laat Edi je de kant van Ubud zien die je vanaf de hoofdstraat mist: de Gunung Lebah-tempel bij de rivier, het dorp Penestanan met zijn kunstenaars, een warung voor babi guling of nasi campur, en de Pura Taman Saraswati met de lotusvijver.",
    ],
    highlights: [
      "Campuhan Ridge Walk bij zonsopgang",
      "Pura Gunung Lebah aan de samenkomst van twee rivieren",
      "Kunstenaarsdorp Penestanan",
      "Ontbijt of vroege lunch in een lokale warung",
      "Pura Taman Saraswati met lotusvijver",
    ],
    programma: [
      "06:30 · Ophalen bij je verblijf in Ubud",
      "07:00 · Wandeling over de Campuhan-heuvelkam (± 1,5 uur)",
      "08:45 · Pura Gunung Lebah en koffie met uitzicht",
      "09:30 · Penestanan en ateliers",
      "11:00 · Warung-lunch en Pura Taman Saraswati",
      "12:00 · Terug bij je verblijf",
    ],
    tips: [
      "Er is geen schaduw op de heuvelkam; ga vroeg en neem water mee.",
      "Het pad is grotendeels verhard en ook geschikt voor kinderen.",
      "Wil je meer wandelen? Edi kent de rijstveldroute bij Sari Organik en de Sayan-vallei.",
    ],
  },
  {
    slug: "ubud-met-kinderen",
    title: "Ubud met kinderen: Monkey Forest, Bali Bird Park & rijstveldwandeling",
    short: "Apen, neushoornvogels en een korte wandeling: een dag die kinderen niet vergeten",
    category: "familie",
    region: "Ubud & Gianyar",
    duration: "Hele dag (± 8 uur)",
    priceFrom: 55,
    priceUnit: "auto",
    image: "/images/tours/monkey-forest.jpg",
    imageAlt: "Makaak zit op een houten reling in het Monkey Forest van Ubud",
    bestTime: "Het hele jaar; start vroeg zodat het Monkey Forest nog koel en rustig is.",
    intro: [
      "Bali is een fantastisch eiland voor kinderen, en rond Ubud kun je er een dag van maken die nooit lang saai is. Je begint tussen de apen van het Monkey Forest, waar de kleintjes met open mond kijken naar baby-makaken.",
      "Daarna een korte wandeling door de rijstvelden met uitleg van Edi over hoe rijst groeit, een lunch met zwembad, en in de middag het Bali Bird Park met vrij rondvliegende neushoornvogels, papegaaien en de zeldzame Bali-spreeuw.",
    ],
    highlights: [
      "Sacred Monkey Forest",
      "Korte rijstveldwandeling op kindertempo",
      "Lunch bij een restaurant met zwembad",
      "Bali Bird Park met vrije vluchtshows",
      "Optioneel: Balinese dansles of ijs bij Gelato Secrets",
    ],
    programma: [
      "08:30 · Ophalen bij je verblijf",
      "09:15 · Monkey Forest",
      "10:45 · Rijstveldwandeling (± 45 min)",
      "12:00 · Lunch met zwembad (eigen rekening)",
      "14:00 · Bali Bird Park",
      "16:00 · IJsje in Ubud",
      "16:30 · Terug bij je verblijf",
    ],
    tips: [
      "Kinderzitje beschikbaar op verzoek; zeg het bij het boeken.",
      "Neem zwemkleding mee voor het zwembad bij de lunch.",
      "Voer de apen niet en houd flesjes en snacks in de tas.",
    ],
  },
  {
    slug: "sidemen-vallei",
    title: "Sidemen: rijstveldwandeling, weefatelier & uitzicht op de Agung",
    short: "Het Ubud van dertig jaar geleden, met de heilige berg als achtergrond",
    category: "natuur",
    region: "Oost-Bali (Karangasem)",
    duration: "Hele dag (± 9 uur)",
    priceFrom: 60,
    priceUnit: "auto",
    image: "/images/tours/sidemen-vallei.jpg",
    imageAlt: "Groene rijstvelden in de Sidemen-vallei met een palm en bewolkte lucht",
    bestTime: "Ochtend: de Agung is het vaakst wolkenvrij tot ongeveer 10:00 uur.",
    intro: [
      "De Sidemen-vallei aan de voet van de Gunung Agung is wat Ubud was voordat het druk werd: rijstvelden tot aan de horizon, een rivier die door de vallei snijdt en dorpen waar de tijd langzamer gaat.",
      "Met een lokale gids wandel je twee uur over de dijkjes, langs boeren en eendenkuddes. Daarna bezoek je een atelier waar songket en endek worden geweven, en drink je arak of koffie met uitzicht op de vulkaan.",
    ],
    highlights: [
      "Rijstveldwandeling van ± 2 uur met lokale gids",
      "Uitzicht op de Gunung Agung",
      "Weefatelier voor songket en endek",
      "Lunch met uitzicht over de vallei",
      "Optioneel: Pura Besakih of Tukad Cepung erbij",
    ],
    programma: [
      "07:00 · Ophalen bij je verblijf",
      "09:00 · Aankomst Sidemen, start van de wandeling",
      "11:00 · Weefatelier en dorp",
      "12:30 · Lunch met uitzicht (eigen rekening)",
      "14:00 · Bukit Cinta of Tukad Cepung (optioneel)",
      "16:00 · Terug bij je verblijf",
    ],
    tips: [
      "Pet, zonnebrand en dichte schoenen voor de wandeling.",
      "Sidemen is ook een prachtige plek om twee nachten te blijven; Edi past het programma daarop aan.",
      "Vraag in het weefatelier gerust naar de prijzen; kopen mag, hoeft niet.",
    ],
  },
];

export function tourBySlug(slug: string) {
  return TOURS.find((tour) => tour.slug === slug);
}

export function toursByCategory(category: Category) {
  return TOURS.filter((tour) => tour.category === category);
}

export const POPULAR_TOURS = TOURS.filter((tour) => tour.popular);

/** Tours uit dezelfde categorie (aangevuld met andere) voor onder aan een tourpagina. */
export function relatedTours(tour: Tour, count = 3) {
  const sameCategory = TOURS.filter(
    (t) => t.slug !== tour.slug && t.category === tour.category,
  );
  const others = TOURS.filter(
    (t) => t.slug !== tour.slug && t.category !== tour.category,
  );
  return [...sameCategory, ...others].slice(0, count);
}
